import { GoogleGenAI, Type, Schema } from "@google/genai";
import { LaundryOrderResult } from "../types";

const processFileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the Data-URI prefix (e.g. "data:image/jpeg;base64,")
      const base64Data = result.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const calculatePrice = (weight: number): number => {
  if (isNaN(weight)) return 0;
  
  // Pricing logic derived strictly from spreadsheet:
  // < 6kg uses the 4kg rate: 4.55 / 4 = 1.1375
  // >= 6kg uses the 6kg rate: 9.10 / 6 = 1.5166666...
  
  if (weight < 6) {
    return Number((weight * 1.1375).toFixed(2));
  } else {
    // 9.10 divided by 6 provides the exact multiplier for the standard rate
    const standardRate = 9.10 / 6;
    return Number((weight * standardRate).toFixed(2));
  }
};

export const extractLaundryData = async (
  serviceName: string,
  weightPhoto: File,
  customerPhoto: File
): Promise<LaundryOrderResult> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const weightBase64 = await processFileToBase64(weightPhoto);
  const customerBase64 = await processFileToBase64(customerPhoto);

  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      laundry_service_name: { type: Type.STRING },
      shopify_order_number: { type: Type.STRING },
      customer_name: { type: Type.STRING },
      delivery_address: { type: Type.STRING },
      laundry_weight_kg: { 
        type: Type.NUMBER, 
        description: "The numerical weight in kg derived from the analog scale." 
      },
      extraction_confidence_score: { 
        type: Type.NUMBER,
        description: "A score between 0 and 1 indicating confidence."
      },
    },
    required: [
      "laundry_service_name",
      "shopify_order_number",
      "customer_name",
      "delivery_address",
      "laundry_weight_kg",
      "extraction_confidence_score"
    ],
  };

  const systemInstruction = `
    You are an expert, multimodal AI data extraction engine specializing in commercial laundry batch processing. 
    Your primary task is to process two distinct images and a manual Service Name input for a single order.

    INPUT PROCESSING INSTRUCTIONS:
    1. laundry_service_name: Use the value provided in the text prompt exactly.
    2. Laundry Weight Photo (Image 1): 
       - This photo contains a 'SPID' brand ANALOG DIAL SCALE with a 100kg capacity.
       - The scale face is white/cream with a red center. The pointer is RED.
       - The numbers are arranged clockwise on the outer ring (0, 5, 10, ... 100).
       - Locate the RED POINTER.
       - Read the value indicated by the tip of the red pointer on the numbered scale.
       - Extract the precise numerical weight in kilograms (kg).
       - If the pointer is between tick marks, estimate to one decimal place (e.g., 12.5).
    3. Customer Data Photo (Image 2): Use OCR and contextual analysis to extract the 'shopify_order_number', 'customer_name', and 'delivery_address' from the shipping label or order form.

    OUTPUT GENERATION LOGIC:
    A. Extract the numerical value for 'laundry_weight_kg'.
    B. Extract the strings for customer data.
    C. If any field is unclear/unreadable, return a best guess but lower the confidence score.
  `;

  // We explicitly map the files to the prompt structure
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: {
      parts: [
        { text: `Process this order. Laundry Service Name: ${serviceName}` },
        {
          inlineData: {
            mimeType: weightPhoto.type,
            data: weightBase64
          }
        },
        { text: "Above is the Laundry Weight Photo (Analog Scale)." },
        {
          inlineData: {
            mimeType: customerPhoto.type,
            data: customerBase64
          }
        },
        { text: "Above is the Customer Data Photo (Shipping Label)." }
      ]
    },
    config: {
      systemInstruction: systemInstruction,
      responseMimeType: "application/json",
      responseSchema: schema,
      temperature: 0.1, // Low temperature for factual extraction
    }
  });

  const text = response.text;
  if (!text) {
    throw new Error("No data returned from Gemini.");
  }

  try {
    const data = JSON.parse(text) as LaundryOrderResult;
    // Add timestamp client-side as it's not generated by AI
    data.timestamp = Date.now();
    
    // Calculate Price using the shared logic
    const weightVal = typeof data.laundry_weight_kg === 'number' ? data.laundry_weight_kg : 0;
    data.price = calculatePrice(weightVal);

    // Attach original image sources for history display
    // Construct valid Data URIs
    data.weight_image_src = `data:${weightPhoto.type};base64,${weightBase64}`;
    data.customer_image_src = `data:${customerPhoto.type};base64,${customerBase64}`;

    return data;
  } catch (e) {
    console.error("Failed to parse JSON", text);
    throw new Error("Failed to parse response from AI.");
  }
};